[project]
name = "yapper"
version = "0.2.0b1"
description = "Simple python parser converting python docstrings to .astro files for the Astro static site generator."
authors = [
    {name = "Gareth Simons", email = "garethsimons@me.com"},
]
license-expression = "MIT"
dependencies = ["docstring-parser<1.0,>=0.13", "PyYAML<7.0,>=6.0", "dominate<3.0.0,>=2.6.0", "python-slugify<7.0.0,>=6.1.1", "Markdown<4.0.0,>=3.3.6"]
requires-python = ">=3.9,<4.0"

[project.urls]
Documentation =  "https://github.com/benchmark-urbanism/yapper"
Issues = "https://github.com/benchmark-urbanism/yapper/issues"

[project.optional-dependencies]
[tool.pdm]
[tool.pdm.dev-dependencies]
dev = [
    "pytest>=7.1.1",
]

[build-system]
requires = ["pdm-pep517>=0.12.0"]
build-backend = "pdm.pep517.api"

[project.scripts]
mycli = "yapper.__init__:cli"