name: publish dev package
on:
  push:
    tags:
      - "*.*.*[ab]*"
jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pdm-project/setup-pdm@main
        name: Setup PDM
        with:
          python-version: 3.9
          prerelease: true
          enable-pep582: true
      - name: publish-dev
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.YAPPER_PYPI_TEST }}
        run: |
          pdm install
          pdm run build
          pdm run twine upload -r testpypi dist/*
