name: publish dev package
on:
  push:
    tags:
      - "*.*.*[ab]*"
jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pdm-project/setup-pdm@main
        name: Setup PDM
        with:
          python-version: 3.9
          prerelease: true
          enable-pep582: true
      - name: Install and build
        run: |
          pdm install
          pdm run build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository_url: https://test.pypi.org/legacy/
          user: ${{ secrets.PYPI_USERNAME }}
          password: ${{ secrets.YAPPER_PYPI_TEST }}
