name: publish dev package
on:
  push:
    tags:
      - "*.*.*[ab]*"
jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pdm-project/setup-pdm@main
        name: Setup PDM
        with:
          python-version: 3.9
          prerelease: true
          enable-pep582: true
      - name: Install dependencies
        run: |
          pdm install
      - name: Publish
        run: |
          pdm run build
          pdm run twine upload -r testpypi dist/* -u ${{secrets.PYPI_USERNAME}} -p ${{secrets.YAPPER_PYPI_TEST}}
