name: publish package
on:
  push:
    tags-ignore:
      - "*.*.*[ab]*"
jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pdm-project/setup-pdm@main
        name: Setup PDM
        with:
          python-version: 3.9
          prerelease: true
          enable-pep582: true
      - name: Install dependencies
        run: |
          pdm install
          pdm plugin add pdm-publish
      - name: Publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.YAPPER_PYPI }}
        run: |
          pdm run build
          pdm run twine upload dist/*
